// ═══════════════════════════════════════════════════════════════
// ReportEngine — HTML backtest report generator
// Creates downloadable HTML reports with charts and tables
// ═══════════════════════════════════════════════════════════════

export class ReportEngine {
  generate(data) {
    const {
      metrics, trades, equityHistory, candles, benchmark,
      mcSummary, wfSummary, settings, strategyName, timestamp,
    } = data;

    const tradeBreakdown = this._tradeTable(trades);
    const equityChartSVG = this._equitySVG(equityHistory, benchmark?.equityCurve);
    const metricsHTML = this._metricsTable(metrics);
    const benchmarkHTML = benchmark ? this._benchmarkTable(metrics, benchmark) : '';
    const mcHTML = mcSummary ? this._mcSection(mcSummary) : '';
    const wfHTML = wfSummary ? this._wfSection(wfSummary) : '';
    const riskHTML = this._riskSection(metrics);
    const settingsHTML = this._settingsTable(settings);

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Backtest Report — ${strategyName || 'Strategy'}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background:#0d1117; color:#c9d1d9; line-height:1.5; padding:20px; max-width:1200px; margin:0 auto; }
  h1 { font-size:24px; color:#58a6ff; margin-bottom:4px; }
  h2 { font-size:16px; color:#58a6ff; margin:24px 0 12px; padding-bottom:6px; border-bottom:1px solid #21262d; }
  h3 { font-size:13px; color:#8b949e; margin:16px 0 8px; text-transform:uppercase; letter-spacing:1px; }
  .subtitle { color:#8b949e; font-size:13px; margin-bottom:20px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(200px, 1fr)); gap:10px; margin-bottom:16px; }
  .card { background:#161b22; border:1px solid #21262d; padding:12px; border-radius:4px; }
  .card-label { font-size:11px; color:#8b949e; text-transform:uppercase; letter-spacing:1px; margin-bottom:4px; }
  .card-value { font-size:18px; font-weight:600; }
  .up { color:#3fb950; } .down { color:#f85149; } .neu { color:#58a6ff; }
  table { width:100%; border-collapse:collapse; font-size:12px; margin-bottom:16px; }
  th { text-align:left; padding:6px 8px; background:#161b22; color:#8b949e; border-bottom:1px solid #21262d; font-size:11px; text-transform:uppercase; letter-spacing:0.5px; }
  td { padding:5px 8px; border-bottom:1px solid #21262d; }
  tr:hover { background:#161b22; }
  .badge { display:inline-block; padding:2px 8px; font-size:10px; border-radius:3px; font-weight:600; }
  .badge-green { background:rgba(63,185,80,0.15); color:#3fb950; }
  .badge-red { background:rgba(248,81,73,0.15); color:#f85149; }
  .badge-blue { background:rgba(88,166,255,0.15); color:#58a6ff; }
  .equity-chart { width:100%; height:200px; background:#161b22; border:1px solid #21262d; border-radius:4px; overflow:hidden; }
  .footer { margin-top:30px; padding-top:12px; border-top:1px solid #21262d; font-size:11px; color:#484f58; }
  .two-col { display:grid; grid-template-columns:1fr 1fr; gap:16px; }
  @media (max-width:768px) { .two-col,.grid { grid-template-columns:1fr; } }
</style>
</head>
<body>
<h1>Backtest Report</h1>
<div class="subtitle">${strategyName || 'Custom Strategy'} — Generated ${timestamp || new Date().toISOString().slice(0, 19)}</div>

<h2>Performance Summary</h2>
${metricsHTML}

${benchmarkHTML}

<h2>Equity Curve</h2>
<div class="equity-chart">${equityChartSVG}</div>

<h2>Risk Metrics</h2>
${riskHTML}

${mcHTML}
${wfHTML}

<h2>Trade Breakdown</h2>
${tradeBreakdown}

<h2>Settings</h2>
${settingsHTML}

<div class="footer">Report generated by Backtest Engine. Data is based on simulated/historical market conditions and does not guarantee future results.</div>
</body>
</html>`;
  }

  _metricsTable(m) {
    if (!m) return '';
    const fmt = (v, pct = false) => pct ? (v * 100).toFixed(2) + '%' : (typeof v === 'number' ? v.toFixed(2) : v);
    const cls = (v) => v > 0 ? 'up' : v < 0 ? 'down' : 'neu';

    return `<div class="grid">
      <div class="card"><div class="card-label">Total Return</div><div class="card-value ${cls(m.totalReturn)}">${fmt(m.totalReturn, true)}</div></div>
      <div class="card"><div class="card-label">Sharpe Ratio</div><div class="card-value ${cls(m.sharpe)}">${fmt(m.sharpe)}</div></div>
      <div class="card"><div class="card-label">Sortino Ratio</div><div class="card-value ${cls(m.sortino)}">${fmt(m.sortino || 0)}</div></div>
      <div class="card"><div class="card-label">Max Drawdown</div><div class="card-value down">${fmt(m.maxDrawdown, true)}</div></div>
      <div class="card"><div class="card-label">Win Rate</div><div class="card-value">${fmt(m.winRate, true)}</div></div>
      <div class="card"><div class="card-label">Profit Factor</div><div class="card-value ${cls(m.profitFactor - 1)}">${fmt(m.profitFactor)}</div></div>
      <div class="card"><div class="card-label">Total Trades</div><div class="card-value neu">${m.totalTrades}</div></div>
      <div class="card"><div class="card-label">CAGR</div><div class="card-value ${cls(m.cagr)}">${fmt(m.cagr, true)}</div></div>
      <div class="card"><div class="card-label">Expectancy</div><div class="card-value ${cls(m.expectancy)}">${fmt(m.expectancy)}</div></div>
      <div class="card"><div class="card-label">Total Fees</div><div class="card-value down">${fmt(m.totalFees)}</div></div>
    </div>`;
  }

  _benchmarkTable(metrics, bm) {
    if (!bm) return '';
    const fmt = (v) => (v * 100).toFixed(2) + '%';
    return `<h2>Strategy vs Buy & Hold</h2>
    <table>
      <tr><th>Metric</th><th>Strategy</th><th>Buy & Hold</th><th>Alpha</th></tr>
      <tr><td>Total Return</td><td>${fmt(metrics.totalReturn)}</td><td>${fmt(bm.totalReturn)}</td><td class="${metrics.totalReturn > bm.totalReturn ? 'up' : 'down'}">${fmt(metrics.totalReturn - bm.totalReturn)}</td></tr>
      <tr><td>Max Drawdown</td><td>${fmt(metrics.maxDrawdown)}</td><td>${fmt(bm.maxDrawdown)}</td><td class="${metrics.maxDrawdown < bm.maxDrawdown ? 'up' : 'down'}">${fmt(bm.maxDrawdown - metrics.maxDrawdown)}</td></tr>
      <tr><td>Sharpe</td><td>${metrics.sharpe.toFixed(3)}</td><td>${bm.sharpe.toFixed(3)}</td><td class="${metrics.sharpe > bm.sharpe ? 'up' : 'down'}">${(metrics.sharpe - bm.sharpe).toFixed(3)}</td></tr>
      <tr><td>CAGR</td><td>${fmt(metrics.cagr)}</td><td>${fmt(bm.cagr)}</td><td class="${metrics.cagr > bm.cagr ? 'up' : 'down'}">${fmt(metrics.cagr - bm.cagr)}</td></tr>
    </table>`;
  }

  _riskSection(m) {
    if (!m) return '';
    const interpret = (val, thresholds) => {
      if (val >= thresholds[0]) return ['badge-green', thresholds[2]];
      if (val >= thresholds[1]) return ['badge-blue', thresholds[3]];
      return ['badge-red', thresholds[4]];
    };

    const [varCls, varText] = interpret(-m.var95, [-3, -5, 'Low Risk', 'Moderate', 'High Risk']);
    const [omegaCls, omegaText] = interpret(m.omega, [1.5, 1.0, 'Strong', 'Neutral', 'Weak']);
    const [marCls, marText] = interpret(m.mar, [1.0, 0.5, 'Excellent', 'Acceptable', 'Poor']);

    return `<div class="grid">
      <div class="card"><div class="card-label">VaR 95%</div><div class="card-value">${(m.var95 || 0).toFixed(2)}%</div><span class="badge ${varCls}">${varText}</span></div>
      <div class="card"><div class="card-label">CVaR 95%</div><div class="card-value">${(m.cvar95 || 0).toFixed(2)}%</div></div>
      <div class="card"><div class="card-label">Omega Ratio</div><div class="card-value">${(m.omega || 0).toFixed(2)}</div><span class="badge ${omegaCls}">${omegaText}</span></div>
      <div class="card"><div class="card-label">MAR Ratio</div><div class="card-value">${(m.mar || 0).toFixed(2)}</div><span class="badge ${marCls}">${marText}</span></div>
      <div class="card"><div class="card-label">Calmar Ratio</div><div class="card-value">${(m.calmar || 0).toFixed(2)}</div></div>
      <div class="card"><div class="card-label">Kelly %</div><div class="card-value">${(m.kelly * 100).toFixed(1)}%</div></div>
    </div>`;
  }

  _tradeTable(trades) {
    if (!trades || !trades.length) return '<p style="color:#8b949e">No trades recorded.</p>';
    const maxShow = 100;
    const shown = trades.slice(-maxShow);
    let html = `<p style="font-size:11px;color:#8b949e;margin-bottom:8px">Showing last ${shown.length} of ${trades.length} trades</p>`;
    html += '<table><thead><tr><th>#</th><th>Dir</th><th>Entry</th><th>Exit</th><th>Size</th><th>PnL</th><th>Fees</th><th>Bars</th><th>Reason</th></tr></thead><tbody>';
    for (const t of shown) {
      const cls = t.pnl >= 0 ? 'up' : 'down';
      const dirCls = t.direction === 'long' ? 'badge-green' : 'badge-red';
      html += `<tr>
        <td>${t.id}</td>
        <td><span class="badge ${dirCls}">${t.direction.toUpperCase()}</span></td>
        <td>${t.entryPrice.toFixed(2)}</td>
        <td>${t.exitPrice.toFixed(2)}</td>
        <td>${t.size.toFixed(4)}</td>
        <td class="${cls}">${t.pnl.toFixed(2)}</td>
        <td>${t.fees.toFixed(2)}</td>
        <td>${t.exitBar - t.entryBar}</td>
        <td>${t.reason}</td>
      </tr>`;
    }
    html += '</tbody></table>';
    return html;
  }

  _equitySVG(equity, benchmark) {
    if (!equity || equity.length < 2) return '<svg></svg>';
    const W = 1200, H = 200, pad = 10;

    const allVals = [...equity, ...(benchmark || [])];
    const min = Math.min(...allVals);
    const max = Math.max(...allVals);
    const range = max - min || 1;

    const toX = (i, len) => pad + (i / (len - 1)) * (W - 2 * pad);
    const toY = (v) => H - pad - ((v - min) / range) * (H - 2 * pad);

    let bmPath = '';
    if (benchmark && benchmark.length > 1) {
      bmPath = benchmark.map((v, i) => `${i === 0 ? 'M' : 'L'}${toX(i, benchmark.length).toFixed(1)},${toY(v).toFixed(1)}`).join('');
    }

    const eqPath = equity.map((v, i) => `${i === 0 ? 'M' : 'L'}${toX(i, equity.length).toFixed(1)},${toY(v).toFixed(1)}`).join('');
    const isUp = equity[equity.length - 1] >= equity[0];
    const color = isUp ? '#3fb950' : '#f85149';

    return `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
      ${bmPath ? `<path d="${bmPath}" fill="none" stroke="#484f58" stroke-width="1.5" stroke-dasharray="4"/>` : ''}
      <path d="${eqPath}" fill="none" stroke="${color}" stroke-width="2"/>
      <text x="${pad}" y="16" fill="#8b949e" font-size="11" font-family="monospace">${max.toFixed(0)}</text>
      <text x="${pad}" y="${H - 4}" fill="#8b949e" font-size="11" font-family="monospace">${min.toFixed(0)}</text>
      ${bmPath ? '<text x="' + (W - 120) + '" y="16" fill="#484f58" font-size="11" font-family="monospace">-- Buy &amp; Hold</text>' : ''}
      <text x="${W - 120}" y="32" fill="${color}" font-size="11" font-family="monospace">— Strategy</text>
    </svg>`;
  }

  _mcSection(summary) {
    if (!summary) return '';
    return `<h2>Monte Carlo Summary</h2>
    <div class="grid">
      <div class="card"><div class="card-label">Runs</div><div class="card-value neu">${summary.totalRuns}</div></div>
      <div class="card"><div class="card-label">Mean Return</div><div class="card-value">${summary.returns.mean.toFixed(2)}%</div></div>
      <div class="card"><div class="card-label">95% Tail</div><div class="card-value down">${summary.tailLoss95.toFixed(2)}%</div></div>
      <div class="card"><div class="card-label">Positive Rate</div><div class="card-value">${(summary.positiveRate * 100).toFixed(0)}%</div></div>
      <div class="card"><div class="card-label">Mean Sharpe</div><div class="card-value">${summary.sharpe.mean.toFixed(3)}</div></div>
      <div class="card"><div class="card-label">Stability</div><div class="card-value">${summary.stabilityScore.toFixed(3)}</div></div>
    </div>`;
  }

  _wfSection(summary) {
    if (!summary) return '';
    return `<h2>Walk-Forward Analysis</h2>
    <div class="grid">
      <div class="card"><div class="card-label">Windows</div><div class="card-value neu">${summary.totalWindows}</div></div>
      <div class="card"><div class="card-label">OOS Positive Rate</div><div class="card-value">${(summary.oosPositiveRate * 100).toFixed(0)}%</div></div>
      <div class="card"><div class="card-label">Avg OOS Return</div><div class="card-value">${summary.avgOosReturn.toFixed(2)}%</div></div>
      <div class="card"><div class="card-label">Consistency</div><div class="card-value"><span class="badge badge-${summary.consistency === 'Good' ? 'green' : summary.consistency === 'Fair' ? 'blue' : 'red'}">${summary.consistency}</span></div></div>
    </div>`;
  }

  _settingsTable(settings) {
    if (!settings) return '';
    let html = '<table>';
    for (const [key, value] of Object.entries(settings)) {
      if (typeof value === 'object') continue;
      html += `<tr><td style="color:#8b949e">${key}</td><td>${value}</td></tr>`;
    }
    html += '</table>';
    return html;
  }
}
